version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - garden-backend-network
    environment:
    # ！！注意修改密码！！
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
     # ！！注意修改密码！！
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-mydir:/mydir
      - mysql-datadir:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的 sql 文件放在这里
      - mysql-source:/docker-entrypoint-initdb.d
      - ./mysql/init.sh:/init.sh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - garden-backend-network
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      HIDE_PHP_VERSION: 0
      PMA_QUERYHISTORYDB: 1
    restart: always
    ports:
      - 8081:80
  redis:
    image: redis:6
    container_name: redis
    command: redis-server --bind 0.0.0.0 --daemonize no --protected-mode no --requirepass 6985Rj6jQpVEWDH0
    networks:
      - garden-backend-network
    restart: always
    ports:
      - "6379:6379"

# 默认目录：
# linux /var/lib/docker/volumes/
volumes:
  mysql-mydir:
  mysql-datadir:
  mysql-source:

networks:
  garden-backend-network:
    external: true