version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /docker-volumes/mysql/mydir:/mydir
      - /docker-volumes/mysql/datadir:/var/lib/mysql
      - /docker-volumes/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /docker-volumes/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=yourpassword"
      - "MYSQL_DATABASE=yourdbname"
      - "TZ=Asia/Shanghai"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8090:8090"
    environment:
      PMA_HOST: 127.0.0.1:3306
      MYSQL_ROOT_PASSWORD: yourpassword
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
