services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker-volumes/home/www:/home/www
      - /docker-volumes/nginx/log:/var/log/nginx
      - /docker-volumes/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /docker-volumes/nginx/html:/usr/share/nginx/html
